CREATE TABLE IF NOT EXISTS types (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    type_name VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS pokemons (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    pokemon_name VARCHAR(255) UNIQUE,
    type_one VARCHAR(255) REFERENCES types (type_name),
    type_two VARCHAR(255) REFERENCES types (type_name)
);

CREATE TABLE IF NOT EXISTS trainers (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    trainer_name VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS owned_pokemons (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    pokemon VARCHAR(255) REFERENCES pokemons (pokemon_name),
    trainer VARCHAR(255) REFERENCES trainers (trainer_name)
);
