CREATE TABLE IF NOT EXISTS pokemon (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255),
    type_one_id INTEGER REFERENCES types (id),
    type_two_id INTEGER REFERENCES types (id)
);

CREATE TABLE IF NOT EXISTS types (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS trainer (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS owned_pokemon (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    pokemon_id INTEGER REFERENCES pokemon (id),
    trainer_id INTEGER REFERENCES trainer (id)
);
